import React, { useEffect, useState } from 'react';
import {
  Box, Typography, Card, CardContent, Grid, Chip, CircularProgress,
  Table, TableBody, TableCell, TableHead, TableRow, Button,
} from '@mui/material';
import { Security as SecurityIcon } from '@mui/icons-material';
import { getGovernanceRules, getComplianceReports, generateComplianceReport, getWorkflowRuns } from '../services/api';
import { formatDate } from '../utils/helpers';

export default function GovernancePage() {
  const [rules, setRules] = useState<any[]>([]);
  const [reports, setReports] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [latestRunId, setLatestRunId] = useState<string | null>(null);

  useEffect(() => {
    Promise.all([
      getGovernanceRules().then((r) => setRules(r.data.results || [])),
      getComplianceReports().then((r) => setReports(r.data.results || [])),
      getWorkflowRuns().then((r) => {
        const completed = r.data.results?.find((w: any) => w.status === 'COMPLETED');
        if (completed) setLatestRunId(completed.id);
      }),
    ]).finally(() => setLoading(false));
  }, []);

  const handleGenerate = async () => {
    if (!latestRunId) return;
    setGenerating(true);
    try {
      await generateComplianceReport(latestRunId);
      setTimeout(() => {
        getComplianceReports().then((r) => setReports(r.data.results || []));
        setGenerating(false);
      }, 3000);
    } catch { setGenerating(false); }
  };

  if (loading) return <Box sx={{ display: 'flex', justifyContent: 'center', p: 4 }}><CircularProgress /></Box>;

  return (
    <Box>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Box>
          <Typography variant="h4">Governance & Compliance</Typography>
          <Typography variant="body2" color="text.secondary">Safety rules, compliance reports, and audit controls</Typography>
        </Box>
        <Button variant="contained" startIcon={generating ? <CircularProgress size={20} color="inherit" /> : <SecurityIcon />}
          onClick={handleGenerate} disabled={generating || !latestRunId}>
          Generate Compliance Report
        </Button>
      </Box>

      <Grid container spacing={3}>
        <Grid item xs={12}>
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>Active Governance Rules</Typography>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell>Rule Name</TableCell>
                    <TableCell>Type</TableCell>
                    <TableCell>Severity</TableCell>
                    <TableCell>Status</TableCell>
                    <TableCell>Description</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {rules.length > 0 ? rules.map((rule) => (
                    <TableRow key={rule.id}>
                      <TableCell sx={{ fontWeight: 600 }}>{rule.name}</TableCell>
                      <TableCell><Chip label={rule.rule_type} size="small" variant="outlined" /></TableCell>
                      <TableCell><Chip label={rule.severity} size="small" color={rule.severity === 'critical' ? 'error' : rule.severity === 'warning' ? 'warning' : 'info'} /></TableCell>
                      <TableCell><Chip label={rule.is_active ? 'Active' : 'Inactive'} size="small" color={rule.is_active ? 'success' : 'default'} /></TableCell>
                      <TableCell sx={{ maxWidth: 400 }}>{rule.description}</TableCell>
                    </TableRow>
                  )) : (
                    <TableRow>
                      <TableCell colSpan={5} align="center">
                        <Typography color="text.secondary" sx={{ py: 2 }}>
                          Default governance rules are enforced by the Safety Governance Agent:
                          PHI Detection, Low Evidence Check, Minor Patient Guard, High Risk Contradiction Check, Rate Limiting
                        </Typography>
                      </TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </Grid>

        <Grid item xs={12}>
          <Card>
            <CardContent>
              <Typography variant="h6" gutterBottom>Compliance Reports</Typography>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell>Report ID</TableCell>
                    <TableCell>Type</TableCell>
                    <TableCell>Summary</TableCell>
                    <TableCell>Generated By</TableCell>
                    <TableCell>Date</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {reports.map((report) => (
                    <TableRow key={report.id}>
                      <TableCell sx={{ fontFamily: 'monospace', fontSize: '0.8rem' }}>{report.id?.slice(0, 8)}...</TableCell>
                      <TableCell><Chip label={report.report_type} size="small" /></TableCell>
                      <TableCell>{report.summary}</TableCell>
                      <TableCell>{report.generated_by}</TableCell>
                      <TableCell sx={{ fontSize: '0.8rem' }}>{formatDate(report.created_at)}</TableCell>
                    </TableRow>
                  ))}
                  {reports.length === 0 && (
                    <TableRow><TableCell colSpan={5} align="center" sx={{ py: 3 }}>No compliance reports generated yet</TableCell></TableRow>
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </Grid>
      </Grid>
    </Box>
  );
}
